#pragma once

// from glfw3.h
#define RCKT_MOUSE_BUTTON_1         0
#define RCKT_MOUSE_BUTTON_2         1
#define RCKT_MOUSE_BUTTON_3         2
#define RCKT_MOUSE_BUTTON_4         3
#define RCKT_MOUSE_BUTTON_5         4
#define RCKT_MOUSE_BUTTON_6         5
#define RCKT_MOUSE_BUTTON_7         6
#define RCKT_MOUSE_BUTTON_8         7
#define RCKT_MOUSE_BUTTON_LAST      RCKT_MOUSE_BUTTON_8
#define RCKT_MOUSE_BUTTON_LEFT      RCKT_MOUSE_BUTTON_1
#define RCKT_MOUSE_BUTTON_RIGHT     RCKT_MOUSE_BUTTON_2
#define RCKT_MOUSE_BUTTON_MIDDLE    RCKT_MOUSE_BUTTON_3