name: Build for Windows

on:
  push:
    branches:
      - git-actions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Run Premake Script
      run: |
        dir
        cd scripts
        .\Win-GenProjects.bat
        cd ..

    - name: Build Solution
      run: |
        msbuild.exe .\rocket.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143 
