name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Premake
      run: |
        Invoke-WebRequest -Uri https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip -OutFile premake.zip
        Expand-Archive -Path premake.zip -DestinationPath vendors/premake/bin/

    - name: Run Premake Script
      run: |
        cd scripts
        .\Win-GenProjects.bat
        cd ..

    - name: Build Rocket Engine
      run: msbuild /p:Configuration=Release /m /p:Platform=x64 /p:ProjectName=rocket-engine

    - name: Build Rocket Editor
      run: msbuild /p:Configuration=Release /m /p:Platform=x64 /p:ProjectName=rocket-editor

