name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./rocket/rocket.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      run: |
        git clone https://github.com/moon3fire/rocket --recursive
        cd rocket/scripts
        .\Win-GenProjects.bat
        cd ..
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Premake
      run: |
        cd scripts
        ./Win-GenProjects.bat
        cd ..

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        pwd
        ls
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
